---
function:
    name: omni-tac-event-processor-${self:provider.stage}
    handler: src/tacEventProcessor.handler
    timeout: 
    runtime: nodejs14.x
    layers:
        - { Ref: OmniTacIndexLayerLambdaLayer }
    package:
        patterns:
            - "!**/*"
            - "src/tacEventProcessor.js"
            - "src/shared/*"
    events:
        - existingS3:
            bucket: ${ssm:/omni-tac-index/${self:provider.stage}/event-processor/bucket-name}
            events: 
                - s3:ObjectCreated:*
            rules:
                - suffix: jobconsol.csv
                - prefix: cw-csv
        - existingS3:
            bucket: ${ssm:/omni-tac-index/${self:provider.stage}/event-processor/bucket-name}
            events: 
                - s3:ObjectCreated:*
            rules:
                - suffix: JobShipment.csv
                - prefix: cw-csv