---
function:
  name: omni-tac-hawb-output-file-handler-${self:provider.stage}
  handler: src/tacHAWBOutputFileHandler.handler
  timeout: 500
  runtime: nodejs18.x
  layers:
    - { Ref: OmniTacIndexLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/tacHAWBOutputFileHandler.js"
  events:
    - stream:
        arn: arn:aws:dynamodb:us-east-1:332281781429:table/omni-tac-hawb-output-table-temp/stream/2023-10-09T17:02:18.899
        batchSize: 1
        startingPosition: LATEST
