---
function:
  name: omni-tac-hawb-output-file-handler-${self:provider.stage}
  handler: src/tacHAWBOutputFileHandler.handler
  timeout: 500
  runtime: nodejs18.x
  layers:
    - { Ref: OmniTacIndexLayerLambdaLayer }
  package:
    patterns:
      - "!**/*"
      - "src/tacHAWBOutputFileHandler.js"
  events:
    - sqs:
          arn: ${ssm:/omni-tac-index/${self:provider.stage}/hawb-output-serializer-fifo-queue-arn}
          batchSize: 1
