---
function:
  name: omni-tac-index-trigger-test-${self:provider.stage}
  handler: src/tacIndexTriggerTest.handler
  timeout: 30
  runtime: nodejs14.x
  vpc:
    securityGroupIds:
      - ${ssm:/omni-default/${self:provider.stage}/sgId}
    subnetIds:
      - ${ssm:/omni-default/${self:provider.stage}/subnetA}
      - ${ssm:/omni-default/${self:provider.stage}/subnetB}
  layers:
    - { Ref: OmniTacIndexLayerLambdaLayer }
  environment:
    SNS_TOPIC_ARN: ${ssm:/omni-reports/${self:provider.stage}/error-notification/sns/arn}
	  REGION: ${self:provider.region}
  package:
    patterns:
      - "!**/*"
      - "src/tacIndexTriggerTest.js"
  events:
    - http:
        path: testTac
        method: post
        cors: true
        private: false
