env                                           = "dev"
region                                        = "us-east-1"
aws_account_number                            = "332281781429"
profile                                       = "Omni"
omni_tac_event_bucket_name                    = "stage-cw-tables"