OmniTacIndexBatchTaskExecutionRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: omni-tac-index-taskexec-role-${self:provider.stage}
    AssumeRolePolicyDocument:
      Statement:
        - Effect: Allow
          Principal:
            Service: [ecs-tasks.amazonaws.com]
          Action: ["sts:AssumeRole"]
    Path: /
    Policies:
      - PolicyName: AmazonECSTaskExecutionRolePolicy
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - "ecr:GetAuthorizationToken"
                - "ecr:BatchCheckLayerAvailability"
                - "ecr:GetDownloadUrlForLayer"
                - "ecr:BatchGetImage"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
              Resource: "*"
      - PolicyName: omni-tac-index-ecs-task-s3-get-policy
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
                - s3:PutObject
              Resource:
                - ${ssm:/omni-tac-index/${self:provider.stage}/s3.logBucket.arn}
                - ${ssm:/omni-tac-index/${self:provider.stage}/s3.logBucket.arn}/*
OmniTacIndexJobDefinition:
  Type: AWS::Batch::JobDefinition
  Properties:
    JobDefinitionName: omni-tac-index-job-definition-${self:provider.stage}
    Type: container
    RetryStrategy:
      Attempts: 1
    PlatformCapabilities:
      - FARGATE
    ContainerProperties:
      Command:
        - node
        - server.js
      ResourceRequirements:
        - Value: 4
          Type: VCPU
        - Value: 8192
          Type: MEMORY
      FargatePlatformConfiguration:
        PlatformVersion: 1.3.0
      LogConfiguration:
        LogDriver: awslogs
        Options:
          awslogs-group: !Ref OmniTacIndexBatchLogGroup
          awslogs-region: !Ref AWS::Region
          awslogs-stream-prefix: omni-tac-index-logs
      ExecutionRoleArn: !GetAtt "OmniTacIndexBatchTaskExecutionRole.Arn"
      JobRoleArn: !GetAtt "OmniTacIndexBatchTaskExecutionRole.Arn"
      Image:
        Fn::Join:
          - ""
          - - Ref: AWS::AccountId
            - .dkr.ecr.
            - Ref: AWS::Region
            - ".amazonaws.com/omni-tac-index-"
            - ${self:provider.stage}
            - ":"
            - latest
      NetworkConfiguration:
        AssignPublicIp: ENABLED

OmniTacIndexBatchLogGroup:
  Type: AWS::Logs::LogGroup
  Properties:
    LogGroupName: omni-tac-index-log-group-${self:provider.stage}
    RetentionInDays: 7
